project:
  type: website
  output-dir: docs

website:
  title: "BROOKLIN BECKER"
  page-navigation: false
  navbar:
    background: "light"
    left:
      - href: index.qmd
        text: Home
      - text: "CV"
        file: git_cv.pdf
      - academicpapers.qmd
    page-footer:
      center:
        - icon: github
          href: https://github.com/brooklinbecker
      border: true
      background: "light"
        

format:
  html:
    theme: lux
    css: styles.css
    toc: false

editor: visual


