project:
  type: website
  output-dir: docs

website:
  title: "BROOKLIN BECKER"
  page-navigation: true
  navbar:
    background: "light"
    left:
      - academicpapers.qmd
    page-footer:
      right:
        - icon: github
          href: https://github.com/brooklinbecker
      border: true
      background: "light"
        

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual


